import type { ServerInstanceSnapshot } from "../packages/contracts/src/index.ts";
import { ServerRuntimeManager } from "../components/server/runtime/src/manager.ts";
import type { SpawnServerProcess } from "../components/server/runtime/src/process.ts";
import { buildServerLaunchPlan } from "../components/server/runtime/src/profiles/index.ts";
import assert from "node:assert/strict";
import type { ChildProcessWithoutNullStreams } from "node:child_process";
import { resolve } from "node:path";
import { PassThrough } from "node:stream";
import test from "node:test";
import {
  createMemoryFileSystem,
  FakeServerProcess,
  java17,
  java21,
  java25,
  settings,
  vanillaInstance,
} from "./server-runtime-fixtures.ts";

await test("Quilt installer runs once and hands off to the generated launcher directory", async () => {
  const rootPath = "C:/SeaShard/servers/instance-quilt-runtime";
  const instance: ServerInstanceSnapshot = {
    ...vanillaInstance,
    id: "instance-quilt-runtime",
    name: "Quilt",
    rootPath,
    coreJarPath: `${rootPath}/quilt-latest.jar`,
    serverType: "quilt",
    gameVersion: "latest",
    coreArtifactFileName: "quilt-latest.jar",
    artifactSha256: "8b716edc692a2fa1fb78dbc2f432643be1bc6c867e5605f36f691f44257120ca",
  };
  const plan = buildServerLaunchPlan(instance, settings, "win32");
  const { fileSystem, files } = createMemoryFileSystem(
    new Map([[instance.coreJarPath, "installer"]]),
  );
  const children: FakeServerProcess[] = [];
  const spawnCalls: Array<{
    command: string;
    arguments_: readonly string[];
    options: Parameters<SpawnServerProcess>[2];
  }> = [];
  const manager = new ServerRuntimeManager({
    listInstances: async () => [instance],
    scanJavaInstallations: async () => [java21],
    readSettings: async () => settings,
    fileSystem,
    spawnProcess: (command, arguments_, options) => {
      const child = new FakeServerProcess();
      const index = children.push(child) - 1;
      spawnCalls.push({ command, arguments_, options });
      queueMicrotask(() => child.emit("spawn"));
      if (index === 0) {
        setImmediate(() => {
          for (const sentinel of plan.preparation!.sentinels) files.set(sentinel, "installed");
          child.finish(0, null);
        });
      }
      return child as unknown as ChildProcessWithoutNullStreams;
    },
  });

  await manager.start(instance.id);
  assert.equal(spawnCalls.length, 2);
  assert.deepEqual(spawnCalls[0]!.arguments_, plan.preparation!.arguments);
  assert.equal(spawnCalls[0]!.options.cwd, resolve(rootPath));
  assert.deepEqual(spawnCalls[1]!.arguments_, plan.arguments);
  assert.equal(spawnCalls[1]!.options.cwd, resolve(rootPath, "server"));
  assert.equal(files.get(resolve(rootPath, "server", "eula.txt")), "eula=true\n");
  assert.equal(files.get(resolve(rootPath, "server", "server.properties")), "server-port=25566\n");

  await manager.stop(instance.id);
  assert.equal((children[1]!.stdin as PassThrough).read()?.toString(), "stop\n");
  children[1]!.finish(0, null);
  await manager.dispose();
});

await test("NeoForge installs with Java 25 and stores heap settings in user_jvm_args.txt", async () => {
  const rootPath = "C:/SeaShard/servers/instance-neoforge-runtime";
  const artifactName = "neoforge-26.1.0.0-alpha.1+snapshot-1-installer.jar";
  const instance: ServerInstanceSnapshot = {
    ...vanillaInstance,
    id: "instance-neoforge-runtime",
    name: "NeoForge",
    rootPath,
    coreJarPath: `${rootPath}/server.jar`,
    serverType: "neoforge",
    gameVersion: "26.1",
    coreArtifactFileName: artifactName,
  };
  const plan = buildServerLaunchPlan(instance, settings, "win32");
  const classPathEntry = resolve(rootPath, "libraries", "fixture.jar");
  const { fileSystem, files } = createMemoryFileSystem(
    new Map([[instance.coreJarPath, "installer"]]),
  );
  const children: FakeServerProcess[] = [];
  const spawnCalls: Array<{
    command: string;
    arguments_: readonly string[];
    options: Parameters<SpawnServerProcess>[2];
  }> = [];
  const manager = new ServerRuntimeManager({
    listInstances: async () => [instance],
    scanJavaInstallations: async () => [java21, java25],
    readSettings: async () => settings,
    fileSystem,
    spawnProcess: (command, arguments_, options) => {
      const child = new FakeServerProcess();
      const index = children.push(child) - 1;
      spawnCalls.push({ command, arguments_, options });
      queueMicrotask(() => child.emit("spawn"));
      if (index === 0) {
        setImmediate(() => {
          for (const sentinel of plan.preparation!.sentinels) files.set(sentinel, "installed");
          files.set(plan.jvmArgumentFile!.path, "# generated by NeoForge\n# -Xmx4G\n");
          files.set(
            plan.preparation!.runtimeArgumentFile!,
            "-classpath\nlibraries/fixture.jar\nnet.neoforged.fml.startup.Server\n",
          );
          files.set(classPathEntry, "library");
          child.finish(0, null);
        });
      }
      return child as unknown as ChildProcessWithoutNullStreams;
    },
  });

  await manager.start(instance.id);
  assert.equal(spawnCalls.length, 2);
  assert.equal(spawnCalls[0]!.command, java25.path);
  assert.deepEqual(spawnCalls[0]!.arguments_, plan.preparation!.arguments);
  assert.equal(spawnCalls[1]!.command, java25.path);
  assert.deepEqual(spawnCalls[1]!.arguments_, plan.arguments);
  assert.equal(
    files.get(plan.jvmArgumentFile!.path),
    [
      "# generated by NeoForge",
      "# -Xmx4G",
      "",
      "# >>> SeaShard managed JVM arguments",
      "-XX:+UseG1GC",
      '"-Dmotd=Hello World"',
      "-Xms1024M",
      "-Xmx2048M",
      "# <<< SeaShard managed JVM arguments",
      "",
    ].join("\n"),
  );

  await manager.stop(instance.id);
  assert.equal((children[1]!.stdin as PassThrough).read()?.toString(), "stop\n");
  children[1]!.finish(0, null);
  await manager.dispose();
});

await test("SpongeForge installs standard Forge, copies the Universal mod, and reuses the runtime", async () => {
  const rootPath = "C:/SeaShard/servers/instance-spongeforge-runtime";
  const artifactName = "spongeforge-26.1.2-64.0.1_19.0.0_RC2627-universal.jar";
  const spongeSha256 = "83320019c99e7d2044f7884677b2e007ef988257633126ae952f2598c0de44df";
  const forgeInstallerSha256 = "c89c563de2e0b8d45c6651de580e2b65b569c52becdb0eeedfd1ab89e60b158d";
  const instance: ServerInstanceSnapshot = {
    ...vanillaInstance,
    id: "instance-spongeforge-runtime",
    name: "SpongeForge",
    rootPath,
    coreJarPath: `${rootPath}/${artifactName}`,
    serverType: "spongeforge",
    gameVersion: "26.1.2",
    coreArtifactFileName: artifactName,
    artifactSha256: spongeSha256,
  };
  const plan = buildServerLaunchPlan(instance, settings, "win32");
  const download = plan.preparation!.downloads![0]!;
  const copy = plan.preparation!.copies![0]!;
  assert.deepEqual(plan.java, {
    major: 25,
    exact: true,
    description: "SpongeForge 26.1.2 / Forge 64.0.1",
  });
  assert.equal(
    download.url,
    "https://maven.minecraftforge.net/net/minecraftforge/forge/26.1.2-64.0.1/forge-26.1.2-64.0.1-installer.jar",
  );
  assert.equal(download.sha256, undefined);
  assert.equal(download.sha256Url, `${download.url}.sha256`);
  assert.equal(download.sha256Path, `${download.path}.sha256`);
  assert.equal(copy.source, resolve(instance.coreJarPath));
  assert.equal(copy.target, resolve(rootPath, "mods", artifactName));
  assert.equal(copy.sha256, undefined);
  assert.deepEqual(plan.preparation!.arguments, [
    "-jar",
    "forge-26.1.2-64.0.1-installer.jar",
    "--installServer",
    ".",
  ]);
  assert.deepEqual(plan.arguments, [
    "@user_jvm_args.txt",
    "@libraries\\net\\minecraftforge\\forge\\26.1.2-64.0.1\\win_args.txt",
    "nogui",
  ]);

  const historicalSpongeForgeRoot = "C:/SeaShard/servers/instance-spongeforge-history";
  const historicalSpongeForge = buildServerLaunchPlan(
    {
      ...vanillaInstance,
      id: "instance-spongeforge-history",
      name: "SpongeForge history",
      rootPath: historicalSpongeForgeRoot,
      coreJarPath: `${historicalSpongeForgeRoot}/spongeforge-history.jar`,
      serverType: "spongeforge",
      gameVersion: "1.21.11",
      coreArtifactFileName: "spongeforge-1.21.11-61.0.6_18.0.0_RC2539-universal.jar",
      artifactSha256: undefined,
    },
    settings,
    "win32",
  );
  assert.deepEqual(historicalSpongeForge.java, {
    major: 21,
    exact: true,
    description: "SpongeForge 1.21.11 / Forge 61.0.6",
  });
  assert.equal(
    historicalSpongeForge.preparation?.downloads?.[0]?.url,
    "https://maven.minecraftforge.net/net/minecraftforge/forge/1.21.11-61.0.6/forge-1.21.11-61.0.6-installer.jar",
  );

  const { fileSystem, files } = createMemoryFileSystem(
    new Map([
      [instance.coreJarPath, "sponge-universal"],
      [download.path, "forge-installer"],
      [download.sha256Path!, `${forgeInstallerSha256}\n`],
    ]),
    new Map([
      [instance.coreJarPath, spongeSha256],
      [download.path, forgeInstallerSha256],
      [copy.target, spongeSha256],
    ]),
  );
  const children: FakeServerProcess[] = [];
  const spawnCalls: Array<{
    command: string;
    arguments_: readonly string[];
    options: Parameters<SpawnServerProcess>[2];
  }> = [];
  let fetchCount = 0;
  const manager = new ServerRuntimeManager({
    listInstances: async () => [instance],
    scanJavaInstallations: async () => [java21, java25],
    readSettings: async () => settings,
    fileSystem,
    fetchPreparationArtifact: async () => {
      fetchCount += 1;
      throw new Error("verified local installer should be reused");
    },
    spawnProcess: (command, arguments_, options) => {
      const child = new FakeServerProcess();
      const index = children.push(child) - 1;
      spawnCalls.push({ command, arguments_, options });
      queueMicrotask(() => child.emit("spawn"));
      if (index === 0) {
        setImmediate(() => {
          for (const sentinel of plan.preparation!.sentinels) {
            if (sentinel !== copy.target) files.set(sentinel, "installed");
          }
          files.set(plan.jvmArgumentFile!.path, "# generated by Forge\n");
          files.set(
            plan.preparation!.runtimeArgumentFile!,
            "-Djava.net.preferIPv6Addresses=system -XX:+UseCompactObjectHeaders -jar forge-26.1.2-64.0.1-shim.jar\n",
          );
          child.finish(0, null);
        });
      }
      return child as unknown as ChildProcessWithoutNullStreams;
    },
  });

  await manager.start(instance.id);
  assert.equal(fetchCount, 0);
  assert.equal(spawnCalls.length, 2);
  assert.equal(spawnCalls[0]!.command, java25.path);
  assert.deepEqual(spawnCalls[0]!.arguments_, plan.preparation!.arguments);
  assert.equal(spawnCalls[1]!.command, java25.path);
  assert.deepEqual(spawnCalls[1]!.arguments_, plan.arguments);
  assert.equal(files.get(copy.target), "sponge-universal");
  assert.equal(files.get(resolve(rootPath, "eula.txt")), "eula=true\n");
  assert.equal(files.get(resolve(rootPath, "server.properties")), "server-port=25566\n");

  await manager.stop(instance.id);
  children[1]!.finish(0, null);
  await manager.start(instance.id);
  assert.equal(spawnCalls.length, 3);
  assert.deepEqual(spawnCalls[2]!.arguments_, plan.arguments);
  await manager.stop(instance.id);
  children[2]!.finish(0, null);
  await manager.dispose();
});

await test("SpongeForge rejects a Forge installer download with the wrong SHA-256", async () => {
  const rootPath = "C:/SeaShard/servers/instance-spongeforge-tampered";
  const artifactName = "spongeforge-26.1.2-64.0.1_19.0.0_RC2627-universal.jar";
  const spongeSha256 = "83320019c99e7d2044f7884677b2e007ef988257633126ae952f2598c0de44df";
  const forgeInstallerSha256 = "c89c563de2e0b8d45c6651de580e2b65b569c52becdb0eeedfd1ab89e60b158d";
  const instance: ServerInstanceSnapshot = {
    ...vanillaInstance,
    id: "instance-spongeforge-tampered",
    name: "SpongeForge tampered",
    rootPath,
    coreJarPath: `${rootPath}/${artifactName}`,
    serverType: "spongeforge",
    gameVersion: "26.1.2",
    coreArtifactFileName: artifactName,
    artifactSha256: spongeSha256,
  };
  const { fileSystem } = createMemoryFileSystem(
    new Map([[instance.coreJarPath, "sponge-universal"]]),
    new Map([[instance.coreJarPath, spongeSha256]]),
  );
  let spawnCount = 0;
  const manager = new ServerRuntimeManager({
    listInstances: async () => [instance],
    scanJavaInstallations: async () => [java25],
    readSettings: async () => settings,
    fileSystem,
    fetchPreparationArtifact: async (url) =>
      url.endsWith(".sha256")
        ? new TextEncoder().encode(`${forgeInstallerSha256}\n`)
        : new TextEncoder().encode("tampered"),
    spawnProcess: () => {
      spawnCount += 1;
      return new FakeServerProcess() as unknown as ChildProcessWithoutNullStreams;
    },
  });

  await assert.rejects(
    manager.start(instance.id),
    /downloaded artifact failed SHA-256 verification/,
  );
  assert.equal(spawnCount, 0);
  assert.equal(manager.get(instance.id).state, "failed");
  await manager.dispose();
});

await test("Youer completes its embedded bootstrap before the managed Java 21 launch", async () => {
  const rootPath = "C:/SeaShard/servers/instance-youer-runtime";
  const instance: ServerInstanceSnapshot = {
    ...vanillaInstance,
    id: "instance-youer-runtime",
    name: "Youer",
    rootPath,
    coreJarPath: `${rootPath}/youer-1.21.1-535.jar`,
    serverType: "youer",
    gameVersion: "1.21.1",
    coreArtifactFileName: "youer-1.21.1-535.jar",
    artifactSha256: "f572a78b85df7f3cf143322ab53844209ec5a75bcfbd2d34978acc4cc68d414b",
  };
  const plan = buildServerLaunchPlan(instance, settings, "win32");
  const { fileSystem, files } = createMemoryFileSystem(
    new Map([[instance.coreJarPath, "youer-bootstrap"]]),
  );
  const children: FakeServerProcess[] = [];
  const spawnCalls: Array<{ command: string; arguments_: readonly string[] }> = [];
  const manager = new ServerRuntimeManager({
    listInstances: async () => [instance],
    scanJavaInstallations: async () => [java25, java21],
    readSettings: async () => settings,
    fileSystem,
    spawnProcess: (command, arguments_) => {
      const child = new FakeServerProcess();
      const index = children.push(child) - 1;
      spawnCalls.push({ command, arguments_ });
      queueMicrotask(() => child.emit("spawn"));
      if (index === 0) {
        setImmediate(() => {
          for (const sentinel of plan.preparation!.sentinels) files.set(sentinel, "installed");
          child.finish(1, null);
        });
      }
      return child as unknown as ChildProcessWithoutNullStreams;
    },
  });

  await manager.start(instance.id);
  assert.equal(spawnCalls.length, 2);
  assert.equal(spawnCalls[0]!.command, java21.path);
  assert.deepEqual(spawnCalls[0]!.arguments_, plan.preparation!.arguments);
  assert.equal(spawnCalls[1]!.command, java21.path);
  assert.deepEqual(spawnCalls[1]!.arguments_, plan.arguments);
  assert.equal(files.get(resolve(rootPath, "eula.txt")), "eula=true\n");
  assert.equal(files.get(resolve(rootPath, "server.properties")), "server-port=25566\n");

  await manager.stop(instance.id);
  children[1]!.finish(0, null);
  await manager.dispose();
});

await test("Mohist completes its EULA-gated bootstrap before the managed heap launch", async () => {
  const rootPath = "C:/SeaShard/servers/instance-mohist-runtime";
  const instance: ServerInstanceSnapshot = {
    ...vanillaInstance,
    id: "instance-mohist-runtime",
    name: "Mohist",
    rootPath,
    coreJarPath: `${rootPath}/mohist-1.20.2-173.jar`,
    serverType: "mohist",
    gameVersion: "1.20.2",
    coreArtifactFileName: "mohist-1.20.2-173.jar",
  };
  const plan = buildServerLaunchPlan(instance, settings, "win32");
  const { fileSystem, files } = createMemoryFileSystem(
    new Map([[instance.coreJarPath, "bootstrap"]]),
  );
  const children: FakeServerProcess[] = [];
  const spawnCalls: Array<{ arguments_: readonly string[] }> = [];
  const manager = new ServerRuntimeManager({
    listInstances: async () => [instance],
    scanJavaInstallations: async () => [java17, java21],
    readSettings: async () => settings,
    fileSystem,
    spawnProcess: (_command, arguments_) => {
      const child = new FakeServerProcess();
      const index = children.push(child) - 1;
      spawnCalls.push({ arguments_ });
      queueMicrotask(() => child.emit("spawn"));
      if (index === 0) {
        setImmediate(() => {
          for (const sentinel of plan.preparation!.sentinels) files.set(sentinel, "installed");
          child.finish(1, null);
        });
      }
      return child as unknown as ChildProcessWithoutNullStreams;
    },
  });

  await manager.start(instance.id);
  assert.equal(spawnCalls.length, 2);
  assert.deepEqual(spawnCalls[0]!.arguments_, plan.preparation!.arguments);
  assert.deepEqual(spawnCalls[1]!.arguments_, plan.arguments);
  assert.equal(files.get(resolve(rootPath, "eula.txt")), "eula=true\n");
  assert.equal(files.get(resolve(rootPath, "server.properties")), "server-port=25566\n");

  await manager.stop(instance.id);
  children[1]!.finish(0, null);
  await manager.dispose();
});

await test("installer exit code zero is rejected when required runtime files are absent", async () => {
  const rootPath = "C:/SeaShard/servers/instance-quilt-incomplete";
  const instance: ServerInstanceSnapshot = {
    ...vanillaInstance,
    id: "instance-quilt-incomplete",
    name: "Quilt incomplete",
    rootPath,
    coreJarPath: `${rootPath}/quilt-latest.jar`,
    serverType: "quilt",
    gameVersion: "latest",
    coreArtifactFileName: "quilt-latest.jar",
    artifactSha256: "8b716edc692a2fa1fb78dbc2f432643be1bc6c867e5605f36f691f44257120ca",
  };
  const { fileSystem } = createMemoryFileSystem(new Map([[instance.coreJarPath, "installer"]]));
  const installer = new FakeServerProcess();
  const manager = new ServerRuntimeManager({
    listInstances: async () => [instance],
    scanJavaInstallations: async () => [java21],
    readSettings: async () => settings,
    fileSystem,
    spawnProcess: () => {
      queueMicrotask(() => installer.emit("spawn"));
      setImmediate(() => installer.finish(0, null));
      return installer as unknown as ChildProcessWithoutNullStreams;
    },
  });

  await assert.rejects(
    manager.start(instance.id),
    /installer exited without complete runtime files/,
  );
  assert.equal(manager.get(instance.id).state, "failed");
  await manager.dispose();
});
